######################################################################
# Automatically generated by qmake (3.0) Fri Dec 11 18:05:43 2015
######################################################################

TEMPLATE = app
TARGET = "Qt Project"
INCLUDEPATH += .

# Input
SOURCES += main.cpp
 QT += widgets