######################################################################
# Automatically generated by qmake (3.0) Fri Dec 18 18:20:29 2015
######################################################################

TEMPLATE = app
TARGET = "Qt Project"
INCLUDEPATH += .

# Input
SOURCES += main.cpp

QT       += core gui
greaterThan(QT_MAJOR_VERSION, 4): QT += widgets